### ISSUE TITLE
TIMEOUT of shippable 

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/WPDS#29]
Shippable only grants 2GB of heap memory to the JVM.

Some of the test cases (TreeMap, HashMap etc) consume a large amount of memory and shippable times out. We need to port the CI to our a different server (probably our own) which grants more memory.
This step may require us to switch to Jenkins.

**Comment by johspaeth** [comment]
Some option to improve the performance of the test execution

```
<forkCount>1.5C</forkCount>
<reuseForks>true</reuseForks>
<argLine>-Xmx8G -Xss128m</argLine>
```

**Comment by mbruns42** [comment]
Small test set was added. Test now need around 16 minutes on Jenkins, and around 24 on Shippable.
