### ISSUE TITLE
Mix of snapshot and release versions

### ISSUE THREAD

**Issue by mbruns42** [CROSSINGTUD/WPDS#32]
When deploying to the soot nexus, we can choose whether we want to deploy to the releases or the snapshot repository. 

Right now the top level pom declares a snapshot version and the modules have fixed versions. 
A special case is the submodule PathExpression

We could either go with 
1) Turn everything into a snapshot version, including PathExpression (does not make that much sense, since we'll have many identical versions)
2) Turn everything into a fixed released version (works, but does not accurately describe how we are building) 
3) Remove PathExpression as a submodule. Build PathExpression seperately, deploy it to the releases. Use it as a dependency and download it from nexus.  (this option is the most work, but will actually get rid of using submodules)

How do we want to proceed?

**Comment by johspaeth** [comment]
The last option, despite it is the most work, makes also most sense. Submodules are pain and annoying, linking to a fixed version seems the better alternative. Now, that we can deploy to nexus, we also can deploy PathExpression individually.

Do you agree?

**Comment by mbruns42** [comment]
Absolutely, I'll do option 3.

**Comment by mbruns42** [comment]
Submodule pathexpression was removed and is built seperately on jenkins, all versions in this project are set to snapshot versions.
