### ISSUE TITLE
Jenkins is adding the boomerangPDS tests to the idealPDS tests

### ISSUE THREAD

**Issue by mbruns42** [CROSSINGTUD/WPDS#35]
This results in a huge amount of tests, see recent [build](https://soot-build.cs.uni-paderborn.de/jenkins/job/boomerang/job/WPDS%20Extensive%20Test/lastBuild/testReport/). This happens in both the WPDS job and the Extensive Test one. 

Maybe this may be resolved by removing the maven profile defaultTests from ideaPDS (see #34).

**Comment by mbruns42** [comment]
Update: Was not resolved by removing the defaultTest profile from idealPDS. Might still be related to that profile in another way.

idealPDS stops executing the extra tests when boomerangPDS is excluded via `mvn verify -pl !boomerangPDS`

Maybe boomerangPDS activates that profile and configures surefire to include those tests and as that profile remains active idealPDS uses it as well?

**Comment by mbruns42** [comment]
The effective pom for idealPDS on Jenkins was checked with `mvn help:effective-pom -pl boomerangPDS,idealPDS`. The result is in this [build](https://soot-build.cs.uni-paderborn.de/jenkins/job/boomerang/job/WPDS-Snapshot/6/console). 

The surefire configuration for idealPDS does not contain the includes, but running `mvn verify -pl boomerangPDS,idealPDS`will make the extra tests show up.

**Comment by mbruns42** [comment]
Researched possible causes for executing tests twice:

- Multiple surefire executions specified in pom (checked effective pom, that's not it)
- Multiple surefire invocations from maven command (not on Jenkins, but shippable command was affected, both in WPDS and CryptoAnalysis)
- Use of plugin that executes tests like cobertura (relevant for CryptoAnalysis, but not here)

**Comment by mbruns42** [comment]
Tests are not actually executed twice, just summed up in report.

**Comment by mbruns42** [comment]
Found out the cause: It's the `reportDirectory` Setting in the `maven-surefire-plugin`. It was set to the same directory (for shippable) in both boomerangPDS and idealPDS causing Jenkins to report duplicate tests. 

I'll try to report tests to the shippleable directory but to seperate folders for boomerangPDS and idealPDS

**Comment by johspaeth** [comment]
That is tricky :1st_place_medal: 

Please also add the directories to the .gitignore.

**Comment by mbruns42** [comment]
This part is fixed. Tests for remaining modules seems not configured correctly, described in #42 .
