### ISSUE TITLE
False negative with basic if-branching

### ISSUE THREAD

**Issue by SvenEV** [CROSSINGTUD/WPDS#56]
When branching is involved, the analysis may become unsound and thus may miss coding mistakes, as shown below.

**This test fails, as expected:**
```Java
@Test
public void test1() {
    File file = new File();
    if (staticallyUnknown()) {
        file.open();
        mustBeInAcceptingState(file); // Correctly fails the test
    }
}
```

**This test does NOT fail, but it should:**
```Java
@Test
public void test2() {
    File file = new File();
    if (staticallyUnknown()) {
        file.open();
    }
    mustBeInAcceptingState(file); // Test succeeds unexpectedly
}
```

**Comment by johspaeth** [comment]
I assume it is related to [this issue](https://github.com/CROSSINGTUD/WPDS/issues/53). 
Could you do me a favor and check if the second test (correctly) fails if you add an arbitrary statement after `file.open()`.

**Comment by SvenEV** [comment]
It does not seem to be directly related as the test still succeeds with an additional statement.  
Here's what I tried:
```Java
@Test
public void test2() {
    File file = new File();
    if (staticallyUnknown()) {
        file.open();
        int x = 1; // Extra statement
    }
    mustBeInAcceptingState(file); // Test succeeds unexpectedly
}
```

**Comment by johspaeth** [comment]
It was a bug in the implementation of the mustBeIn..State() assertion. It should be fixed in the master.
