### ISSUE TITLE
Boomerang bodies to Jimple bodies

### ISSUE THREAD

**Issue by ufarooq** [CROSSINGTUD/WPDS#64]
Hi,

I am trying to use this tool as a pointer analysis for an IFDS analysis. My IFDS analysis is using Jimple bodies, but Boomerang transforms bodies during Pre-transformer. What is recommended way to translate between Jimple/Boomerang? Or Do I need to run my IFDS analysis on Boomerang if I want to use WPDS?

Thanks,
Umar

**Comment by johspaeth** [comment]
Hi Umar, 
you need to apply the [BoomerangPretransformer](https://github.com/CROSSINGTUD/WPDS/blob/da1ebaee7ae5ea6baf30d3a23f5175699d4d61d1/boomerangPDS/src/main/java/boomerang/preanalysis/BoomerangPretransformer.java) before the analysis, and run your analysis on the new Jimple Bodies. For instance, the transformer is used [here](
https://github.com/CROSSINGTUD/CryptoAnalysis/blob/60358d4ecfd59aeead4d56c8a06256cc7b9ccec9/CryptoAnalysis/src/main/java/crypto/HeadlessCryptoScanner.java#L218). 

The transformer just replaces statements such as `call(123)` into two statements `int x = 123; call(x)`. This makes the analysis' flow functions easier to write.

**Comment by ufarooq** [comment]
Thanks for clearing up @johspaeth
